### ISSUE TITLE
Create template/example of how to import morphology/activity from a file

### ISSUE THREAD

**Issue by Helveg** [JustasB/BlenderNEURON#16]
I have a large scale network simulation and I'd like to visually represent a small subsection; There is not really any documentation so I'm struggling. From the videos it seems that I should actually be simulating in NEURON for BlenderNEURON to pick up on the signal. This online approach is completely unfeasible; I have the recorded simulation data in an HDF5 file. Is it possible to feed this to BlenderNEURON in an offline fashion?

**Comment by JustasB** [comment]
Hi again,

Interesting use case. BN was initially designed for the "coupled to NEURON" use case, but I wanted to leave it relatively easy to add adapters for other simulators, or in your use case, pre-recorded simulation data.

You should be able to hack the methods of the [BlenderNode class](https://github.com/JustasB/BlenderNEURON/blob/master/blenderneuron/blender/blendernode.py#L8)

In Blender's Python console, it's instantiated in the `bpy.types.Object.BlenderNEURON_node` variable.

![image](https://user-images.githubusercontent.com/10732358/104666970-1a8c6a80-56a3-11eb-9fc1-a5992b90e2f2.png)


Most likely, you could modify the [import_groups_from_neuron](https://github.com/JustasB/BlenderNEURON/blob/master/blenderneuron/blender/blendernode.py#L103) method to read the HDF5 file instead of making an RCP call to NEURON.

In the method, the call to `from_full_NEURON_group` expects a JSON formatted version of morphology/activity for the sections.

If you convert your HDF5 data to the JSON format that method expects using Blender's python, then you should be able to perform the task all within Blender.

An alternative approach could be to replace the NEURON RCP node code (the methods listed [here](https://github.com/JustasB/BlenderNEURON/blob/7297e6aa45722f35908b707d0020b0519a6bc60d/blenderneuron/nrn/neuronnode.py#L30) ) with code that reads your HDF5 file and formats the morphology/animation data in the same JSON format.

I can document what the JSON format should look like, but I would suggest placing a few print statements in the above `import_groups_from_neuron` method (with a few-compartment cell + few ms of activity) to get a quick sense.
